### ISSUE TITLE
User Story 7: Prioritize and categorize tasks

### ISSUE THREAD

**Issue by Pur3-MAlice** [Pur3-MAlice/Pom-To-Do-Ro#8]
As a user, I want to be able to prioritize and categorize tasks and view them in a to-do list.

**Comment by Pur3-MAlice** [comment]
User Story 7 Tasks:

- [x] Task 3.3: Create a UI for viewing and managing tasks.  
- [x] Task 3.4: Implement task completion functionality.  
- [x] Task 3.5: Develop task prioritization and categorization features.
